name: Pets
version: "${pom.version}"
api: ["1.0.9"]
author: PetteriM1
main: me.petterim1.pets.Main
description: Pets plugin for Nukkit
website: https://github.com/PetteriM1/Pets/

commands:
  pet:
    description: Pets command
    usage: "/pet"
    permission: pets.manage
  callpet:
    description: Call your pet
    usage: "/callpet"
    permission: pets.call

permissions:
  pets.manage:
    description: "Allows user to manage pets"
    default: op
  pets.call:
    description: "Allows user to call a pet"
    default: true
